### ISSUE TITLE
feature: count number of tokens

### ISSUE THREAD

**Issue by ayaka14732** [ztjhz/ChatGPTFreeApp#12]
It would be more intuitive for users if they can see how many tokens they have used.

> To see how many tokens are in a text string without making an API call, use OpenAI’s [tiktoken](https://github.com/openai/tiktoken) Python library. Example code can be found in the OpenAI Cookbook’s guide on [how to count tokens with tiktoken](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb).

These libraries can be used to calculate the number of tokens:

- Python: [tiktoken](https://github.com/openai/tiktoken/blob/main/README.md) (or alternatively [GPT2TokenizerFast](https://huggingface.co/docs/transformers/model_doc/gpt2#transformers.GPT2TokenizerFast))
- JavaScript: [gpt-3-encoder](https://www.npmjs.com/package/gpt-3-encoder)
- .NET / C#: [GPT Tokenizer](https://github.com/dluc/openai-tools)
- Java: [gpt2-tokenizer-java](https://github.com/hyunwoongko/gpt2-tokenizer-java)
- PHP: [GPT-3-Encoder-PHP](https://github.com/CodeRevolutionPlugins/GPT-3-Encoder-PHP)

**Comment by ayaka14732** [comment]
@ztjhz Is this implemented?

**Comment by ztjhz** [comment]
Yes!

**Comment by SamuelMiller** [comment]
How do I view the token counter https://freechatgpt.chat/ ? Is it available for private APIs? I don't see it.

**Comment by ztjhz** [comment]
We can implement a token counter for each message in the future, but currently the token counter is counting the submitted messages and truncating it to the maximum tokens allows.
