### ISSUE TITLE
feature: customise `temperature` and other API parameters

### ISSUE THREAD

**Issue by ayaka14732** [ztjhz/ChatGPTFreeApp#14]
https://platform.openai.com/docs/api-reference/chat/create

> `temperature`: What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.

There are other useful parameters such as `presence_penalty` as well.

**Comment by SamuelMiller** [comment]
It would be great to be able to allow users to set max_tokens parameters when they are using their own Chatgpt API key with the web app https://freechatgpt.chat/. By default, the number of tokens the model can return is 4096  (prompt tokens). What is the default max_tokens set for freechatgpt?

**Comment by ayaka14732** [comment]
@SamuelMiller According to the documentation (https://platform.openai.com/docs/api-reference/chat/create), the default value for `max_tokens` is inf, which means that there is no restriction on the length. However, the maximum sequence length (input+output) is 4096 tokens.
