### ISSUE TITLE
feature: copy code when generating

### ISSUE THREAD

**Issue by Honoka55** [ztjhz/ChatGPTFreeApp#17]
Copy code button is disabled when generating.

Original ChatGPT allows copy code when generating.

**Comment by ztjhz** [comment]
Thanks for flagging this up! I'm on it and will get it fixed ASAP. By the way, just a heads up, the code actually gets copied to your clipboard even if the button text did not change to `copied`.

**Comment by Honoka55** [comment]
Seems not copied now

**Comment by ztjhz** [comment]
Thank you for your patience. The bug has been fixed.
