### ISSUE TITLE
feature: Enhance Error Messages to Indicate Max Request Tokens

### ISSUE THREAD

**Issue by saliksik** [ztjhz/ChatGPTFreeApp#23]
Hey Team!

I noticed that when we reach the limit of 4,096 tokens, the error message displayed is not very descriptive, and just says "Failed to fetch". This could lead to confusion and it would be beneficial to enhance this error message to indicate that we have hit the maximum request tokens.

Thus, I suggest modifying the error message to something like "Request Token Limit Reached. Please reduce the number of tokens in your request." This would make it easier for developers and users to take action and resolve the issue.

Let me know what you think, and if there are any suggestions or concerns. Thanks!

**Comment by ztjhz** [comment]
Thank you for raising this up. We have actually already implemented the error message.

![Error Message](https://user-images.githubusercontent.com/59118459/223056276-a876299a-e213-46dd-80a9-ec2031890184.jpg)

Failed to fetch probably means there is a network error.
