### ISSUE TITLE
feature: customise free API endpoint

### ISSUE THREAD

**Issue by ayaka14732** [ztjhz/ChatGPTFreeApp#36]
As our main free API endpoint has sadly reached the quota, we need to add an option for users to customise the free API endpoint, so that people can share their free API endpoint within a small group of users.

**Comment by SamuelMiller** [comment]
Great idea. I think this is a great project which encourages people to generously share, democratizing access. As I mentioned elsewhere, if you provide basic instructions on how to set up the ChatGPTfree apt on other hosting services, the project could spread.

**Comment by ztjhz** [comment]
This has just been implemented!
