### ISSUE TITLE
documentation: Github Pages

### ISSUE THREAD

**Issue by saliksik** [ztjhz/ChatGPTFreeApp#37]
Hi!

Can you provide a documentation detailing the step-by-step guide on how to deploy this on Github Pages?

Thank you.

**Comment by andrewc0de** [comment]
Deploying this on Vercel is incredibly easy, as demonstrated by my personal fork here: https://chatgptapi-free.vercel.app/.

To get started, simply navigate to the Vercel website and access the dashboard. From there you can deploy your own fork of this repository with just a few clicks. Just be sure to promote any syncs to production once you're finished.
