### ISSUE TITLE
Oops, the stream is locked right now. Please try again。

### ISSUE THREAD

**Issue by txmu** [ztjhz/ChatGPTFreeApp#38]
When I use the [Free ChatGPT](freechatgpt.chat) , "**Oops, the stream is locked right now . Please try again**." always appears if the "current" is less than "limit".**But I can use the free api with curl.**

**Comment by andrewc0de** [comment]
The actual ChatGPT API is overloaded / facing issues.

**Comment by ztjhz** [comment]
@txmu I just made some changes. Let me know if the issue is fixed.

**Comment by txmu** [comment]
![IMG_20230307_232257](https://user-images.githubusercontent.com/71213934/223469346-6fd977d3-5c27-4f60-bc30-343380b7d005.jpg)

**It's still like this.But I can still use the free api with curl.**This is strange.

**Comment by ztjhz** [comment]
I have implemented a fix for this.
