### ISSUE TITLE
Feature: Resubmitting historical dialogues

### ISSUE THREAD

**Issue by huangjunxin** [ztjhz/ChatGPTFreeApp#4]
On ChatGPT, if you modify a historically sent message, you can resubmit it while deleting the subsequent conversation. However, in your ChatGPTFreeApp there is currently only the **{Save}** button for modifying historical dialogues and it will not do anything.

Would it be considered to make an additional resubmit button **{Save & Submit}** like the official ChatGPT? Thank you for your consideration!

**Comment by ztjhz** [comment]
Thank you for the suggestion! The 'Save & Submit' button has been added.

**Comment by saliksik** [comment]
May I know what is the purpose of another Submit button on the end?

**Comment by ztjhz** [comment]
The second submit button is intended for users who have only used the "save" function while editing or adding messages. This button is specifically for submitting the saved messages only when they have been set up. It separates the act of creating and configuring a message from the act of submitting it to ChatGPT.
