### ISSUE TITLE
[Feature Request] Add option to backup all chats

### ISSUE THREAD

**Issue by SamuelMiller** [ztjhz/ChatGPTFreeApp#40]
Recently, I lost all my chats with the ChatGptFree web app using my private API. It happened when the screen went white. To resolve the issue, I had to clear the cache in the Firefox browser, which wiped out all my previous conversations.

It would be great if there were an option to collect and download all the chats in a single file, such as in a Zip file format, so that users could either access these files offline with a text editor or upload the conversations into a new instance of ChatGptFree.

Thanks for all the hard work!

**Comment by SamuelMiller** [comment]
I just had another incidence of the "white screen of death" where after some time the app interface disappears into the abyss of pure whiteness. I suspect I've lost my conversations again.

**Comment by ztjhz** [comment]
This has been implemented. You can check the side menu for the `Import / Export` button

**Comment by SamuelMiller** [comment]
Great work!
