### ISSUE TITLE
[bug?] The white kiss of death in Firefox

### ISSUE THREAD

**Issue by SamuelMiller** [ztjhz/ChatGPTFreeApp#46]
I just had another incidence of the "white screen of death" in Catalina OS, Firefox, where after some time of interacting with the app, the whole interface disappears into the abyss of pure whiteness--a blank browser window. I am only able to restore my access to https://freechatgpt.chat/ through Firefox by clearing out the cache, which wipes out my conversations. I suspect it is an app bug--corruption of the thread? See https://github.com/ztjhz/ChatGPTFreeApp/issues/40 for my first report on this weird phenomenon.

**Comment by ztjhz** [comment]
Thanks for bringing it up. I'll look into this issue.

**Comment by ztjhz** [comment]
Do you see any errors in the console when you experience the white screen?

**Comment by SamuelMiller** [comment]
I wonder if it relates to reaching the limit of my token?

Here is what the console reports:
```
Could not find the language 'mermaid', did you forget to load/include a language module? index-9890d563.js:346:10332
    Is https://freechatgpt.chat/assets/index-9890d563.js:346
    d https://freechatgpt.chat/assets/index-9890d563.js:347
    u https://freechatgpt.chat/assets/index-9890d563.js:347
    code https://freechatgpt.chat/assets/index-9890d563.js:47617
    My https://freechatgpt.chat/assets/index-9890d563.js:38
    Jx https://freechatgpt.chat/assets/index-9890d563.js:40
    jx https://freechatgpt.chat/assets/index-9890d563.js:40
    hB https://freechatgpt.chat/assets/index-9890d563.js:40
    Mm https://freechatgpt.chat/assets/index-9890d563.js:40
    $x https://freechatgpt.chat/assets/index-9890d563.js:40
    k https://freechatgpt.chat/assets/index-9890d563.js:25
    j https://freechatgpt.chat/assets/index-9890d563.js:25
    (Async: EventHandlerNonNull)
    <anonymous> https://freechatgpt.chat/assets/index-9890d563.js:25
    <anonymous> https://freechatgpt.chat/assets/index-9890d563.js:25
```

**Comment by ztjhz** [comment]
I see. This is a bug related to detecting the language of the code generated by chatgpt. I will get it fixed as soon as possible.

**Comment by SamuelMiller** [comment]
Thanks! I appreciate how quick you folks are in fixing bugs. I can now re-access my previous FreeChatGPT discussions in Firefox.
