### ISSUE TITLE
Remove: Temperature and Presence Penalty

### ISSUE THREAD

**Issue by saliksik** [ztjhz/ChatGPTFreeApp#51]
Hello,

Considering that the aim of this web application is to encourage more non-technical individuals to utilize chat and witness the potential of AI, I suggest that we remove the Temperature and Presence Penalty configuration from the application. These settings are unlikely to be useful to non-technical users. Instead, we should stick to the default settings provided by OpenAI.

For reference, I have included a sample output (using Temperature 2) below.
![Web capture_9-3-2023_194322_freechatgpt chat](https://user-images.githubusercontent.com/122975898/224013998-76f8b0e2-8c74-4608-96a0-2c7c15dcb4d6.jpeg)

**Comment by Yardanico** [comment]
I don't think removing it is a good idea, but maybe it would be good to hide it beneath some toggle like "Enable advanced options"

**Comment by ayaka14732** [comment]
This web application caters to both non-technical individuals seeking a user-friendly experience and advanced users looking for more complex features.
