### ISSUE TITLE
[Feature Request] Save User API Key (via Cookie and/or LocalStorage)

### ISSUE THREAD

**Issue by Deagan** [ztjhz/ChatGPTFreeApp#52]
I clear most of my browser history on browser close, and it seems that the https://freechatgpt.chat site doesn't store my OpenAI API key.

Was there any way to keep this saved (perhaps via Cookie and/or browser LocalStorage) to save the key between sessions?

Would also be nice to keep the chat history if possible!

**Comment by ztjhz** [comment]
Presently, the user API key and the entire chat history are preserved in the browser local storage. In your case that the chat history and api key being lost, it is likely attributable to the clearing of the local storage upon browser closure.

**Comment by Deagan** [comment]
Apologies, this was due to my browser configuration. My Offline Site Data (in Firefox) was indeed clearing on browser close.

I am now able to keep chat history and user API Key through sessions!

Thank you for the amazing frontend!
