### ISSUE TITLE
bug: Console Error Messages

### ISSUE THREAD

**Issue by saliksik** [ztjhz/ChatGPTFreeApp#53]
react-dom.development.js:29840 Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools
react-jsx-dev-runtime.development.js:87 
        
       Warning: Each child in a list should have a unique "key" prop.

Check the render method of `ChatContent`. See https://reactjs.org/link/warning-keys for more information.
    at ChatContent (http://localhost:5173/src/components/Chat/ChatContent/ChatContent.tsx:23:23)
    at main
    at div
    at Chat
    at div
    at App (http://localhost:5173/src/App.tsx:18:31)
printWarning @ react-jsx-dev-runtime.development.js:87

**Comment by ztjhz** [comment]
Thank you for raising it up. I've fixed this.
