### ISSUE TITLE
[Suggestion]：“download chat as image” and “Stop generating” accidental clicks problem？

### ISSUE THREAD

**Issue by kehck** [ztjhz/ChatGPTFreeApp#57]
I often use the "Stop generating" feature on this site, but I keep accidentally clicking on the newly added "download chat as image" button. I suggest moving the "download chat as image" button slightly higher, to the right of the "Save" button.

**Comment by ztjhz** [comment]
I will hide the download chat button during chat generation since it is unlikely that users will need to download chats while the process is ongoing.
