### ISSUE TITLE
feature: clear all chats

### ISSUE THREAD

**Issue by 2dgeneralspam1** [ztjhz/ChatGPTFreeApp#6]
I wanted to reach out and suggest a new feature that I believe would greatly improve the user experience of this ChatGPT Web Clone. As a user of the actual ChatGPT platform, I've come to appreciate the convenience of having a button that clears all chats at once.

I believe that implementing a similar button on the ChatGPT Web Clone platform would make it easier for users to manage their chats and free up storage space, and promote a better overall experience with the application. To complement the button, a confirmation prompt should be added to avoid accidental deletions of important chat history.

As someone who regularly uses ChatGPT, I believe this feature would be a valuable addition to ChatGPT Web Clone and help to make it even more similar to the original platform. Thank you for taking the time to consider my suggestion.

**Comment by huangjunxin** [comment]
I agree with this proposal as well.
